controller_list:
  - name: fake_arm_controller
    type: $(arg execution_type)
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_gripper_controller
    type: $(arg execution_type)
    joints:
      - finger_joint
  - name: fake_wheels_controller
    type: $(arg execution_type)
    joints:
      - left_wheel
      - right_wheel
initial:  # Define initial robot poses.
  - group: arm
    pose: default_arm
  - group: gripper
    pose: default_gripper